version: '3'

services:
  gsv:
    build: .
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis://redis:6379
    volumes:
      - "./players.json:/players.json"
      - "./matches.json:/matches.json"
  redis:
    image: redislabs/rejson
